; Listing generated by Microsoft (R) Optimizing Compiler Version 19.24.28117.0 

	TITLE	C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	?f___@@YAHHHHH@Z				; f___
PUBLIC	?f___cdecl@@YAHHHHH@Z				; f___cdecl
PUBLIC	?f__stdcall@@YGHHHHH@Z				; f__stdcall
PUBLIC	?f__fastcall@@YIHHHHH@Z				; f__fastcall
PUBLIC	?f__vectorcall@@YQHHHHH@Z			; f__vectorcall
PUBLIC	?f__naked@@YAHHHHH@Z				; f__naked
PUBLIC	_main
; Function compile flags: /Odtp
_TEXT	SEGMENT
_main	PROC
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 44
	push	ebp
	mov	ebp, esp
; Line 46
	push	4
	push	3
	push	2
	push	1
	call	?f___@@YAHHHHH@Z			; f___
	add	esp, 16					; 00000010H
; Line 47
	push	4
	push	3
	push	2
	push	1
	call	?f___cdecl@@YAHHHHH@Z			; f___cdecl
	add	esp, 16					; 00000010H
; Line 48
	push	4
	push	3
	push	2
	push	1
	call	?f__stdcall@@YGHHHHH@Z			; f__stdcall
; Line 49
	push	4
	push	3
	mov	edx, 2
	mov	ecx, 1
	call	?f__fastcall@@YIHHHHH@Z			; f__fastcall
; Line 50
	push	4
	push	3
	mov	edx, 2
	mov	ecx, 1
	call	?f__vectorcall@@YQHHHHH@Z		; f__vectorcall
; Line 51
	push	4
	push	3
	push	2
	push	1
	call	?f__naked@@YAHHHHH@Z			; f__naked
	add	esp, 16					; 00000010H
; Line 52
	xor	eax, eax
	pop	ebp
	ret	0
_main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
_d$ = 20						; size = 4
?f__naked@@YAHHHHH@Z PROC				; f__naked
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 40
	mov	eax, 0
?f__naked@@YAHHHHH@Z ENDP				; f__naked
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = -8						; size = 4
_b$ = -4						; size = 4
_c$ = 8							; size = 4
_d$ = 12						; size = 4
?f__vectorcall@@YQHHHHH@Z PROC				; f__vectorcall
; _a$ = ecx
; _b$ = edx
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 30
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _b$[ebp], edx
	mov	DWORD PTR _a$[ebp], ecx
; Line 32
	xor	eax, eax
; Line 33
	mov	esp, ebp
	pop	ebp
	ret	8
?f__vectorcall@@YQHHHHH@Z ENDP				; f__vectorcall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = -8						; size = 4
_b$ = -4						; size = 4
_c$ = 8							; size = 4
_d$ = 12						; size = 4
?f__fastcall@@YIHHHHH@Z PROC				; f__fastcall
; _a$ = ecx
; _b$ = edx
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 24
	push	ebp
	mov	ebp, esp
	sub	esp, 8
	mov	DWORD PTR _b$[ebp], edx
	mov	DWORD PTR _a$[ebp], ecx
; Line 26
	xor	eax, eax
; Line 27
	mov	esp, ebp
	pop	ebp
	ret	8
?f__fastcall@@YIHHHHH@Z ENDP				; f__fastcall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
_d$ = 20						; size = 4
?f__stdcall@@YGHHHHH@Z PROC				; f__stdcall
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 19
	push	ebp
	mov	ebp, esp
; Line 21
	xor	eax, eax
; Line 22
	pop	ebp
	ret	16					; 00000010H
?f__stdcall@@YGHHHHH@Z ENDP				; f__stdcall
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
_d$ = 20						; size = 4
?f___cdecl@@YAHHHHH@Z PROC				; f___cdecl
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 13
	push	ebp
	mov	ebp, esp
; Line 15
	xor	eax, eax
; Line 16
	pop	ebp
	ret	0
?f___cdecl@@YAHHHHH@Z ENDP				; f___cdecl
_TEXT	ENDS
; Function compile flags: /Odtp
_TEXT	SEGMENT
_a$ = 8							; size = 4
_b$ = 12						; size = 4
_c$ = 16						; size = 4
_d$ = 20						; size = 4
?f___@@YAHHHHH@Z PROC					; f___
; File C:\Users\libit\source\repos\SQLite_17\SQLite_17\SQLite_17.cpp
; Line 6
	push	ebp
	mov	ebp, esp
; Line 8
	xor	eax, eax
; Line 9
	pop	ebp
	ret	0
?f___@@YAHHHHH@Z ENDP					; f___
_TEXT	ENDS
END
